/**
 * Skill Self-Improvement Engine
 *
 * Correction-gated loop that rewrites existing skill bodies in-place based on
 * user feedback captured during a conversation turn.
 *
 * Design decisions:
 * - Correction-gated only (no A/B/C classification). Gate: corrections.length > 0.
 * - LLM self-filters: outputs NO_CHANGE when correction does not apply.
 * - Per-process token bucket (3/hour) prevents runaway LLM costs.
 *   Not shared across multiple server instances — each process gets its own budget.
 * - Per-project in-flight deduplication via getSkillSet().
 * - Skills cache DB is ephemeral (recreate-on-mismatch): improvement_count resets
 *   on schema bump. The cap is therefore best-effort only.
 * - autoGenerated is set to false on improvement: improved skills graduate from
 *   auto-cleanup. cleanupStaleAutoSkills will no longer target them.
 * - incrementImprovementCount after saveSkill may fail (DB error), leaving the
 *   file updated but counter undercounted. Accepted: undercounting is preferable
 *   to double-write or rollback.
 */

import { copyFileSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { loadConfigFile } from "../../config/config-file";
import { getSkillManager } from "./manager";

// ============================================================================
// Constants
// ============================================================================

export const MAX_IMPROVEMENTS_PER_SKILL = 5;

/** Path prefix for read-only (Claude Code global) skills. */
const CLAUDE_CODE_SKILLS_DIR = join(homedir(), ".claude");

// ============================================================================
// Token Bucket (3/hour global)
// ============================================================================

const WINDOW_MS = 60 * 60 * 1000;
const MAX_PER_WINDOW = 3;
const bucket: number[] = []; // epoch ms timestamps of recent acquisitions

/**
 * Acquire a rate-limit token from the global 3/hour bucket.
 * Returns true if a token was acquired, false if the bucket is full.
 * Tokens consumed by failed LLM calls are NOT returned (best-effort).
 *
 * @param now - Optional override for current time (injectable for testing).
 */
export function acquireImprovementToken(now = Date.now()): boolean {
  while (bucket.length && now - bucket[0] > WINDOW_MS) bucket.shift();
  if (bucket.length >= MAX_PER_WINDOW) return false;
  bucket.push(now);
  return true;
}

/**
 * Reset the token bucket. FOR TESTING ONLY — not exported in production paths.
 * @internal
 */
export function _resetTokenBucket(): void {
  bucket.length = 0;
}

// ============================================================================
// Per-project in-flight deduplication
// ============================================================================

const skillsBeingImprovedByProject = new Map<string, Set<string>>();

/**
 * Returns the Set of skill names currently being improved for a given project.
 * Exported so plugin and worker can call .clear() on onInit / start().
 */
export function getSkillSet(projectRoot: string): Set<string> {
  if (!skillsBeingImprovedByProject.has(projectRoot)) {
    skillsBeingImprovedByProject.set(projectRoot, new Set());
  }
  return skillsBeingImprovedByProject.get(projectRoot)!;
}

// ============================================================================
// Version helpers
// ============================================================================

/**
 * Increment the patch component of a semver string.
 * Falls back to "1.0.1" for undefined, empty, or malformed input.
 */
export function bumpPatch(v: string | undefined): string {
  if (!v) return "1.0.1";
  const parts = v.split(".").map(Number);
  if (parts.length !== 3 || parts.some(isNaN)) return "1.0.1";
  return `${parts[0]}.${parts[1]}.${parts[2] + 1}`;
}

// ============================================================================
// Editable guard
// ============================================================================

/**
 * Returns false for skills inside ~/.claude (Claude Code read-only global dir).
 * Project-local skills (.clawd/skills/) and global Claw'd skills (~/.clawd/skills/)
 * are considered editable.
 */
export function isEditable(skillPath: string): boolean {
  // Use separator-bounded prefix to avoid false matches like ~/.claudeX/
  return !skillPath.startsWith(CLAUDE_CODE_SKILLS_DIR + "/") && skillPath !== CLAUDE_CODE_SKILLS_DIR;
}

// ============================================================================
// Backup helpers
// ============================================================================

/**
 * Copy the skill file to a timestamped .bak-{ts} file in the same directory.
 * Copies from disk (not from in-memory content) to ensure backup is consistent
 * with what was actually saved.
 *
 * @param skillPath - Absolute path to the SKILL.md file.
 * @param _content  - Ignored (content already on disk). Kept for API consistency.
 * @returns Absolute path to the backup file.
 * @throws If copyFileSync fails (caller should abort write rather than proceed).
 */
export function writeBackup(skillPath: string, _content: string): string {
  const dir = dirname(skillPath);
  const backupPath = join(dir, `SKILL.bak-${Date.now()}-${process.pid}-${Math.random().toString(36).slice(2, 7)}`);
  copyFileSync(skillPath, backupPath);
  return backupPath;
}

/**
 * Restore the skill file from a backup (atomic overwrite).
 * No-op if the backup file no longer exists.
 */
export function restoreBackup(skillPath: string, backupPath: string): void {
  if (!existsSync(backupPath)) return;
  copyFileSync(backupPath, skillPath);
}

// ============================================================================
// Improvement prompt
// ============================================================================

/**
 * Build the prompt sent to the improvement LLM.
 * Uses ===SKILL=== as an unambiguous body separator in the response format.
 */
export function buildImprovementPrompt(
  name: string,
  currentBody: string,
  corrections: string[],
  turnSlice: string,
): string {
  return `You are improving an existing skill based on user corrections from a single
conversation turn. Rewrite the skill body in place. Preserve YAML frontmatter
structure (the caller re-emits frontmatter — output body only).

Rules:
- If the corrections do NOT warrant a change, output exactly: NO_CHANGE
- Otherwise output the new skill body after the separator.
- Keep the skill focused, concise, and actionable.
- Do not remove existing guidance unless it directly conflicts.

## Skill Name
${name}

## Current Skill Body
${currentBody}

## User Corrections (this turn)
${corrections.map((c) => "- " + c.replace(/[<>]/g, "").slice(0, 200)).join("\n")}

## Turn Transcript (condensed, last N messages)
${turnSlice}

## Output Format
Either exactly \`NO_CHANGE\`, or:

===SKILL===
<new skill body markdown>`;
}

// ============================================================================
// Improvement response parser
// ============================================================================

/**
 * Parse the raw LLM response from the improvement prompt.
 *
 * Algorithm:
 * 1. Trim the raw string.
 * 2. If trimmed === "NO_CHANGE" → no_change.
 * 3. Find index of "===SKILL===". If -1 → no_change (defensive).
 * 4. Body = everything after "===SKILL===", trimmed. If empty → no_change.
 * 5. Return { kind: "update", body }.
 */
export function parseImprovementResponse(raw: string): { kind: "no_change" } | { kind: "update"; body: string } {
  const trimmed = raw.trim();
  if (trimmed === "NO_CHANGE") return { kind: "no_change" };
  const idx = raw.indexOf("===SKILL===");
  if (idx === -1) return { kind: "no_change" };
  const body = raw.slice(idx + "===SKILL===".length).trim();
  if (!body) return { kind: "no_change" };
  return { kind: "update", body };
}

// ============================================================================
// Core update function
// ============================================================================

/**
 * Write a new skill body to disk, updating the DB counter.
 *
 * Exact order (must not be reordered):
 * 1. getSkillStats — confirm skill exists in DB.
 * 2. Cap guard — abort if improvement_count >= MAX_IMPROVEMENTS_PER_SKILL.
 * 3. getSkill — load full skill from filesystem.
 * 4. isEditable — abort if path is inside ~/.claude.
 * 5. writeBackup (try/catch) — abort on failure rather than proceeding without backup.
 * 6. saveSkill — atomic write with bumped version and autoGenerated=false.
 *    autoGenerated=false: improved skills graduate from auto-cleanup.
 *    cleanupStaleAutoSkills will no longer target this skill after improvement.
 * 7. incrementImprovementCount — best-effort counter update.
 *
 * @param name        - Skill name (must match DB).
 * @param newBody     - New skill body (markdown, no frontmatter).
 * @param projectRoot - Project root used to look up SkillManager instance.
 */
export async function updateSkillContent(
  name: string,
  newBody: string,
  projectRoot: string,
): Promise<{ ok: boolean; reason?: string }> {
  const sm = getSkillManager(projectRoot);

  // 1. getSkillStats
  const stats = sm.getSkillStats(name);
  if (!stats) return { ok: false, reason: "not_found" };

  // 2. Cap guard
  if (stats.improvement_count >= MAX_IMPROVEMENTS_PER_SKILL) {
    console.log(
      `[SkillImprovement] Cap reached for '${name}' (${stats.improvement_count}/${MAX_IMPROVEMENTS_PER_SKILL})`,
    );
    return { ok: false, reason: "cap_reached" };
  }

  // 3. getSkill (full, including path)
  const existing = sm.getSkill(name);
  if (!existing) return { ok: false, reason: "not_found" };

  // 4. Editable guard
  if (!isEditable(existing.path)) return { ok: false, reason: "read_only" };

  // 5. Backup (BEFORE write) — abort if backup fails
  let backupPath: string;
  try {
    backupPath = writeBackup(existing.path, existing.content);
    console.log(`[SkillImprovement] Backup saved: ${backupPath}`);
  } catch (err) {
    return { ok: false, reason: `backup_failed: ${err}` };
  }

  // 6. saveSkill — bumps version, clears autoGenerated flag
  const saveResult = sm.saveSkill(
    {
      name: existing.name,
      description: existing.description,
      triggers: existing.triggers,
      content: newBody,
      version: bumpPatch(existing.version),
      argumentHint: existing.argumentHint,
      allowedTools: existing.allowedTools,
      autoGenerated: false, // improvement graduates skill from auto-cleanup
    },
    existing.source,
  );

  if (!saveResult.success) {
    restoreBackup(existing.path, backupPath);
    return { ok: false, reason: saveResult.error };
  }

  // 7. DB counter — best-effort (failure leaves counter undercounted, not double-written)
  sm.incrementImprovementCount(name);

  return { ok: true };
}

// ============================================================================
// Main entry point
// ============================================================================

/**
 * Improve a skill based on user corrections captured during a conversation turn.
 *
 * Gates:
 * - corrections.length > 0 (single gate — no A/B/C classification)
 * - Calls CopilotClient with a 30s timeout
 * - Parses NO_CHANGE / body response
 * - Calls updateSkillContent (which enforces cap + backup + editable guards)
 *
 * Fire-and-forget: caller should not await this in the hot path.
 * Errors are swallowed internally — caller's .catch() handler gets them.
 */
export async function improveSkillFromCorrections(
  skillName: string,
  corrections: string[],
  turnSlice: string,
  projectRoot: string,
): Promise<void> {
  // Single gate: no corrections → skip
  if (corrections.length === 0) return;

  // Credential pre-check before consuming a rate-limit token.
  // getCopilotToken() returns null when neither KeyPool nor env vars have a valid key.
  const { getCopilotToken } = await import("../api/provider-config");
  if (!getCopilotToken()) {
    console.log(`[SkillImprovement] No credentials configured — skipping`);
    return;
  }

  // Consume rate-limit token AFTER credential check so no slot is wasted on a
  // guaranteed 401. The caller no longer calls acquireImprovementToken() directly.
  if (!acquireImprovementToken()) {
    console.log(`[SkillImprovement] Rate limit reached (3/hour) — skipping '${skillName}'`);
    return;
  }

  const sm = getSkillManager(projectRoot);
  const existing = sm.getSkill(skillName);
  if (!existing) {
    console.log(`[SkillImprovement] Skill '${skillName}' not found — skipping improvement`);
    return;
  }

  const prompt = buildImprovementPrompt(skillName, existing.content, corrections, turnSlice);

  const memCfg = loadConfigFile().memory;
  const memModel = typeof memCfg === "object" && memCfg?.model ? memCfg.model : "claude-sonnet-4.5";

  const { CopilotClient } = await import("../api/client");
  const client = new CopilotClient("");

  let timeoutId: ReturnType<typeof setTimeout>;
  const timeoutSignal = new Promise<null>((resolve) => {
    timeoutId = setTimeout(() => resolve(null), 30_000);
  });
  const llmCall = client.complete({
    model: memModel,
    messages: [{ role: "user", content: prompt }],
    temperature: 0.2,
    max_tokens: 2000,
  });

  const response = await Promise.race([llmCall, timeoutSignal]);
  clearTimeout(timeoutId!);
  client.close();

  if (!response) {
    console.log(`[SkillImprovement] LLM call timed out for skill '${skillName}'`);
    return;
  }

  const raw = response.choices[0]?.message?.content ?? "";
  const parsed = parseImprovementResponse(raw);

  if (parsed.kind === "no_change") {
    console.log(`[SkillImprovement] NO_CHANGE for skill '${skillName}'`);
    return;
  }

  const result = await updateSkillContent(skillName, parsed.body, projectRoot);
  if (result.ok) {
    console.log(`[SkillImprovement] Updated skill '${skillName}' successfully`);
  } else {
    console.log(`[SkillImprovement] Update failed for '${skillName}': ${result.reason}`);
  }
}
