#!/usr/bin/env bun
/**
 * embed-ui.ts - Generate embedded UI assets module
 *
 * Reads all files from packages/ui/dist/ and generates src/embedded-ui.ts
 * containing a Map of path -> { contentBase64, mimeType } for all UI files.
 *
 * This allows the compiled binary to serve UI assets from memory
 * without needing an external ui/ directory.
 *
 * Usage: bun run scripts/embed-ui.ts
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { extname, join, relative } from "node:path";

const UI_DIST = join(import.meta.dir, "..", "packages", "ui", "dist");
const OUTPUT = join(import.meta.dir, "..", "src", "embedded", "ui.ts");

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".eot": "application/vnd.ms-fontobject",
  ".map": "application/json",
};

function walkDir(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      files.push(...walkDir(fullPath));
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

function getMimeType(filePath: string): string {
  const ext = extname(filePath).toLowerCase();
  return MIME_TYPES[ext] || "application/octet-stream";
}

// Collect all files
const allFiles = walkDir(UI_DIST);
console.log(`[embed-ui] Found ${allFiles.length} files in ${UI_DIST}`);

let totalSize = 0;

// Build the generated TypeScript source
const lines: string[] = [
  "// AUTO-GENERATED by scripts/embed-ui.ts -- DO NOT EDIT",
  `// Generated at: ${new Date().toISOString()}`,
  `// Files: ${allFiles.length}`,
  "",
  "interface EmbeddedAsset {",
  "  contentBase64: string;",
  "  mimeType: string;",
  "  size: number;",
  "}",
  "",
  "const assets: Record<string, EmbeddedAsset> = {",
];

for (const filePath of allFiles) {
  const relPath = "/" + relative(UI_DIST, filePath);
  const content = readFileSync(filePath);
  const base64 = content.toString("base64");
  const mimeType = getMimeType(filePath);
  totalSize += content.length;

  // Escape the path for use as object key
  lines.push(`  ${JSON.stringify(relPath)}: {`);
  lines.push(`    contentBase64: "${base64}",`);
  lines.push(`    mimeType: ${JSON.stringify(mimeType)},`);
  lines.push(`    size: ${content.length},`);
  lines.push("  },");
}

lines.push("};");
lines.push("");
lines.push("// Decoded buffer cache (lazily populated on first access)");
lines.push("const bufferCache = new Map<string, Buffer>();");
lines.push("");
lines.push("/**");
lines.push(" * Get an embedded UI asset by path.");
lines.push(" * Returns null if the path is not found.");
lines.push(" * Buffers are decoded from base64 on first access and cached.");
lines.push(" */");
lines.push("export function getEmbeddedAsset(path: string): { content: Buffer; mimeType: string } | null {");
lines.push("  const asset = assets[path];");
lines.push("  if (!asset) return null;");
lines.push("");
lines.push("  let buffer = bufferCache.get(path);");
lines.push("  if (!buffer) {");
lines.push('    buffer = Buffer.from(asset.contentBase64, "base64");');
lines.push("    bufferCache.set(path, buffer);");
lines.push("  }");
lines.push("");
lines.push("  return { content: buffer, mimeType: asset.mimeType };");
lines.push("}");
lines.push("");
lines.push("/**");
lines.push(" * Check if embedded UI assets are available.");
lines.push(" */");
lines.push(`export const hasEmbeddedUI = ${allFiles.length > 0};`);
lines.push("");
lines.push(`export const embeddedUIFileCount = ${allFiles.length};`);
lines.push(`export const embeddedUITotalSize = ${totalSize};`);
lines.push("");

const output = lines.join("\n");
writeFileSync(OUTPUT, output);

const outputSize = Buffer.byteLength(output);
console.log(`[embed-ui] Generated ${OUTPUT}`);
console.log(`[embed-ui] Total asset size: ${(totalSize / 1024 / 1024).toFixed(1)}MB`);
console.log(`[embed-ui] Generated file size: ${(outputSize / 1024 / 1024).toFixed(1)}MB (base64 overhead)`);
console.log("[embed-ui] Done!");
