#!/usr/bin/env bun
/**
 * embed-ui.ts - Generate embedded UI assets module
 *
 * Walks packages/ui/dist/ and emits src/embedded/ui.ts as a manifest of
 *   path -> { ref: <Bun file import>, mimeType, size }
 *
 * Each asset is brought in via `import f0 from "..." with { type: "file" }`,
 * which Bun resolves to a path string in dev mode and to a virtual
 * `/$bunfs/...` path inside `bun build --compile` binaries. `Bun.file(ref)`
 * then yields a streamable BunFile in either mode.
 *
 * Why this shape (vs. base64 string-literal slabs):
 *   - The previous base64 approach materialised a 7.4MB JS string literal
 *     PLUS a 5.6MB decoded Buffer cache in heap on first request — ~13MB
 *     resident even when no client ever hit static assets.
 *   - BunFile is file-mapped: `new Response(BunFile)` streams via
 *     ReadableStream without a heap copy. Hot path heap drops to ~0;
 *     anonymous RSS savings ≈ 12MB / ~10% of process baseline.
 *
 * Usage: bun run scripts/embed-ui.ts
 */

import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative } from "node:path";

const UI_DIST = join(import.meta.dir, "..", "packages", "ui", "dist");
const OUTPUT = join(import.meta.dir, "..", "src", "embedded", "ui.ts");

mkdirSync(dirname(OUTPUT), { recursive: true });

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".eot": "application/vnd.ms-fontobject",
  ".map": "application/json",
};

function walkDir(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      files.push(...walkDir(fullPath));
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

function getMimeType(filePath: string): string {
  const ext = extname(filePath).toLowerCase();
  return MIME_TYPES[ext] || "application/octet-stream";
}

const allFiles = walkDir(UI_DIST).sort();
console.log(`[embed-ui] Found ${allFiles.length} files in ${UI_DIST}`);

let totalSize = 0;
const importLines: string[] = [];
const manifestLines: string[] = [];
const outputDir = dirname(OUTPUT);

for (let i = 0; i < allFiles.length; i++) {
  const filePath = allFiles[i];
  if (!filePath) continue;
  // Normalize to POSIX separators so HTTP URL `/assets/foo.js` matches the
  // manifest key on Windows-native generator runs (where `relative()` yields
  // backslashes).
  const relPath = "/" + relative(UI_DIST, filePath).split("\\").join("/");
  const stat = statSync(filePath);
  // Source size only — we don't read content into memory at generation time.
  // (Note: readFileSync once for hash-free size total; could use stat.size to
  // avoid the read entirely. Use stat.size — bun build resolves file refs.)
  totalSize += stat.size;
  const mimeType = getMimeType(filePath);

  // Import path is resolved relative to the OUTPUT file's directory so Bun
  // bundler can pick it up regardless of working directory.
  let importPath = relative(outputDir, filePath).split("\\").join("/");
  if (!importPath.startsWith(".")) importPath = "./" + importPath;

  const ident = `f${i}`;
  importLines.push(`import ${ident} from ${JSON.stringify(importPath)} with { type: "file" };`);
  manifestLines.push(
    `  ${JSON.stringify(relPath)}: { ref: ${ident}, mimeType: ${JSON.stringify(mimeType)}, size: ${stat.size} },`,
  );
}

// Sanity touch — ensure the source files are still readable (catches a stale
// manifest where dist was rebuilt but a file was renamed mid-run).
for (const f of allFiles) readFileSync(f, { flag: "r" }).byteLength;

// No generation timestamp — keeps the emitted module byte-reproducible so
// identical inputs produce identical compiled binaries (matters for SLSA /
// attestation / cache hits).
const lines: string[] = [
  "// AUTO-GENERATED by scripts/embed-ui.ts -- DO NOT EDIT",
  `// Files: ${allFiles.length}`,
  "",
  ...importLines,
  "",
  "interface EmbeddedAsset {",
  "  ref: string;",
  "  mimeType: string;",
  "  size: number;",
  "}",
  "",
  "const assets: Record<string, EmbeddedAsset> = {",
  ...manifestLines,
  "};",
  "",
  "/**",
  " * Get an embedded UI asset by path.",
  " * Returns null if the path is not found.",
  " * `content` is a BunFile — file-mapped, streamable directly via",
  " * `new Response(content)` with no heap materialisation.",
  " */",
  "export function getEmbeddedAsset(path: string): { content: Blob; mimeType: string; size: number } | null {",
  "  const asset = assets[path];",
  "  if (!asset) return null;",
  "  return { content: Bun.file(asset.ref), mimeType: asset.mimeType, size: asset.size };",
  "}",
  "",
  "/**",
  " * Check if embedded UI assets are available.",
  " */",
  `export const hasEmbeddedUI = ${allFiles.length > 0};`,
  "",
  `export const embeddedUIFileCount = ${allFiles.length};`,
  `export const embeddedUITotalSize = ${totalSize};`,
  "",
];

const output = lines.join("\n");
writeFileSync(OUTPUT, output);

const outputSize = Buffer.byteLength(output);
console.log(`[embed-ui] Generated ${OUTPUT}`);
console.log(`[embed-ui] Total asset size: ${(totalSize / 1024 / 1024).toFixed(1)}MB (file-mapped, lazy)`);
console.log(`[embed-ui] Generated TS size: ${(outputSize / 1024).toFixed(1)}KB (manifest only)`);
console.log("[embed-ui] Done!");
