#!/usr/bin/env bun
/**
 * embed-cli.ts — Embed the Claude Agent SDK cli.js into a TS module
 *
 * Compresses cli.js with gzip, encodes as base64, and generates
 * src/embedded-cli.ts that extracts it to disk on first use.
 *
 * Usage: bun run scripts/embed-cli.ts
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { gzipSync } from "node:zlib";

const CLI_PATH = join(import.meta.dir, "..", "node_modules", "@anthropic-ai", "claude-agent-sdk", "cli.js");
const TS_OUTPUT = join(import.meta.dir, "..", "src", "embedded", "cli.ts");

if (!existsSync(CLI_PATH)) {
  console.error("[embed-cli] cli.js not found — is @anthropic-ai/claude-agent-sdk installed?");
  process.exit(1);
}

const raw = readFileSync(CLI_PATH);
const compressed = gzipSync(raw, { level: 9 });
const base64 = compressed.toString("base64");

console.log(
  `[embed-cli] Raw: ${(raw.length / 1024 / 1024).toFixed(1)}MB → Compressed: ${(compressed.length / 1024 / 1024).toFixed(1)}MB`,
);

const tsContent = `// AUTO-GENERATED by scripts/embed-cli.ts -- DO NOT EDIT
// Generated at: ${new Date().toISOString()}
// Raw size: ${raw.length} bytes | Compressed: ${compressed.length} bytes

const CLI_JS_GZIP_BASE64 = "${base64}";

export const cliJsCompressedSize = ${compressed.length};
export const cliJsRawSize = ${raw.length};
export { CLI_JS_GZIP_BASE64 };
`;

writeFileSync(TS_OUTPUT, tsContent);
console.log(`[embed-cli] Generated ${TS_OUTPUT} (${(Buffer.byteLength(tsContent) / 1024 / 1024).toFixed(1)}MB)`);
console.log("[embed-cli] Done!");
