#!/usr/bin/env bun
/**
 * embed-cli.ts — Embed the Claude Agent SDK cli.js into a TS module
 *
 * Emits src/embedded/cli.ts containing a `with { type: "file" }` import
 * pointing at node_modules/@anthropic-ai/claude-agent-sdk/cli.js. Bun
 * resolves this to a real disk path in dev mode, and embeds the file into
 * the compiled binary as a virtual `/$bunfs/...` path under
 * `bun build --compile`. Either way `Bun.file(cliRef)` (or fs.readFileSync
 * via Bun's polyfill) yields the bytes.
 *
 * Why this shape (vs. gzip+base64 string slab):
 *   - Old approach baked a 4.7MB base64 string (gzipped cli.js) into the JS
 *     bundle. The string was resident in heap forever and required eager
 *     base64 decode + gunzip on first extraction.
 *   - New approach: cli.js is file-mapped via `Bun.file(cliRef)`. Heap stays
 *     near zero until extraction; readFileSync materialises the bytes only
 *     once when we copy to ~/.clawd/bin/cli.js, then they're released.
 *
 * Trade-off: compiled binary holds raw cli.js (~12.4MB) instead of gzipped
 * (~3.7MB). If `bun build --compile` doesn't compress its embedded files
 * the binary may grow by ~8MB. If that regression is intolerable, pivot to
 * a `cli.js.gz` staging file (gzip pre-bundle, gunzip on extract).
 *
 * No generation timestamp — keeps the emitted module byte-reproducible so
 * identical inputs produce identical compiled binaries (matters for SLSA /
 * attestation / cache hits).
 *
 * Usage: bun run scripts/embed-cli.ts
 */

import { existsSync, mkdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const CLI_PATH = join(import.meta.dir, "..", "node_modules", "@anthropic-ai", "claude-agent-sdk", "cli.js");
const TS_OUTPUT = join(import.meta.dir, "..", "src", "embedded", "cli.ts");

mkdirSync(dirname(TS_OUTPUT), { recursive: true });

if (!existsSync(CLI_PATH)) {
  console.error("[embed-cli] cli.js not found — is @anthropic-ai/claude-agent-sdk installed?");
  process.exit(1);
}

const size = statSync(CLI_PATH).size;
console.log(`[embed-cli] cli.js: ${(size / 1024 / 1024).toFixed(1)}MB`);

// Path is relative to OUTPUT module's directory. cli.ts lives at
// src/embedded/cli.ts, so cli.js at node_modules/@anthropic-ai/claude-agent-sdk/
// resolves as `../../node_modules/@anthropic-ai/claude-agent-sdk/cli.js`.
const tsContent = `// AUTO-GENERATED by scripts/embed-cli.ts -- DO NOT EDIT
// Size: ${size} bytes

import cliRef from "../../node_modules/@anthropic-ai/claude-agent-sdk/cli.js" with { type: "file" };

/**
 * Resolved path / virtual ref for the embedded Claude Agent SDK cli.js.
 * In dev mode this is the real node_modules path; under \`bun build --compile\`
 * this is a virtual \`/$bunfs/...\` path that resolves through Bun.file()
 * and Bun's fs polyfill (readFileSync, etc.).
 */
export { cliRef };

/**
 * Get the embedded cli.js as a Blob — file-mapped, streamable directly.
 * Used by tests for byte-equivalence checks.
 */
export function getCliJsBlob(): Blob {
  return Bun.file(cliRef);
}

export const cliJsSize = ${size};
`;

writeFileSync(TS_OUTPUT, tsContent);
console.log(`[embed-cli] Generated ${TS_OUTPUT} (manifest only — file is embedded by bun build)`);
console.log("[embed-cli] Done!");
