#!/usr/bin/env bun
/**
 * zip-extension.ts - Zip the browser extension and embed as TS module
 *
 * 1. Creates dist/browser-extension.zip from packages/browser-extension/
 * 2. Generates src/embedded-extension.ts with the zip as base64
 *
 * Uses JSZip (no system `zip` command needed — works on Windows/Linux/macOS)
 *
 * Usage: bun run scripts/zip-extension.ts
 */

import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import JSZip from "jszip";

const EXT_DIR = join(import.meta.dir, "..", "packages", "browser-extension");
const ZIP_OUTPUT = join(import.meta.dir, "..", "dist", "browser-extension.zip");
const TS_OUTPUT = join(import.meta.dir, "..", "src", "embedded", "extension.ts");

const EXCLUDE = new Set(["README.md", ".DS_Store"]);
const EXCLUDE_DIRS = new Set([".git", "node_modules"]);

mkdirSync(join(import.meta.dir, "..", "dist"), { recursive: true });
mkdirSync(dirname(TS_OUTPUT), { recursive: true });

// Recursively add files to zip
function addDir(zip: JSZip, dirPath: string, baseDir: string): void {
  for (const entry of readdirSync(dirPath, { withFileTypes: true })) {
    const fullPath = join(dirPath, entry.name);
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      addDir(zip, fullPath, baseDir);
    } else {
      if (EXCLUDE.has(entry.name)) continue;
      const relPath = relative(baseDir, fullPath);
      zip.file(relPath, readFileSync(fullPath));
    }
  }
}

const zip = new JSZip();
addDir(zip, EXT_DIR, EXT_DIR);

const zipBuffer = Buffer.from(await zip.generateAsync({ type: "uint8array", compression: "DEFLATE" }));
writeFileSync(ZIP_OUTPUT, zipBuffer);

const base64 = zipBuffer.toString("base64");
const size = zipBuffer.length;

console.log(`[zip-extension] Created ${ZIP_OUTPUT} (${(size / 1024).toFixed(1)}KB)`);

// Generate embedded TS module
const tsContent = `// AUTO-GENERATED by scripts/zip-extension.ts -- DO NOT EDIT
// Generated at: ${new Date().toISOString()}
// Size: ${size} bytes

const EXTENSION_ZIP_BASE64 = "${base64}";

let _buffer: Buffer | null = null;

/** Get the browser extension zip as a Buffer (decoded lazily and cached). */
export function getExtensionZip(): Buffer {
  if (!_buffer) {
    _buffer = Buffer.from(EXTENSION_ZIP_BASE64, "base64");
  }
  return _buffer;
}

export const extensionZipSize = ${size};
`;

writeFileSync(TS_OUTPUT, tsContent);
console.log(`[zip-extension] Generated ${TS_OUTPUT} (${(Buffer.byteLength(tsContent) / 1024).toFixed(1)}KB)`);
console.log("[zip-extension] Done!");
