#!/usr/bin/env bun
/**
 * zip-extension.ts - Zip the browser extension and embed as TS module
 *
 * 1. Creates dist/browser-extension.zip from packages/browser-extension/
 * 2. Generates src/embedded-extension.ts with the zip as base64
 *
 * Uses JSZip (no system `zip` command needed — works on Windows/Linux/macOS)
 *
 * Usage: bun run scripts/zip-extension.ts
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import JSZip from "jszip";

const EXT_DIR = join(import.meta.dir, "..", "packages", "browser-extension");

const ZIP_OUTPUT = join(import.meta.dir, "..", "dist", "browser-extension.zip");
const TS_OUTPUT = join(import.meta.dir, "..", "src", "embedded", "extension.ts");

const EXCLUDE = new Set(["README.md", ".DS_Store"]);
const EXCLUDE_DIRS = new Set([".git", "node_modules"]);

mkdirSync(join(import.meta.dir, "..", "dist"), { recursive: true });
mkdirSync(dirname(TS_OUTPUT), { recursive: true });

// Recursively add files to zip
function addDir(zip: JSZip, dirPath: string, baseDir: string): void {
  for (const entry of readdirSync(dirPath, { withFileTypes: true })) {
    const fullPath = join(dirPath, entry.name);
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      addDir(zip, fullPath, baseDir);
    } else {
      if (EXCLUDE.has(entry.name)) continue;
      // PKZIP spec (APPNOTE.TXT 4.4.17.1) mandates forward slashes for entry
      // names. On Windows-native runs `relative()` yields backslashes, which
      // unpack as a single flat segment on Linux/macOS and break the
      // browser-extension loader. Normalize to POSIX.
      const relPath = relative(baseDir, fullPath).split("\\").join("/");
      zip.file(relPath, readFileSync(fullPath));
    }
  }
}

const zip = new JSZip();
addDir(zip, EXT_DIR, EXT_DIR);

const zipBuffer = Buffer.from(await zip.generateAsync({ type: "uint8array", compression: "DEFLATE" }));
writeFileSync(ZIP_OUTPUT, zipBuffer);

const size = zipBuffer.length;

console.log(`[zip-extension] Created ${ZIP_OUTPUT} (${(size / 1024).toFixed(1)}KB)`);

// Emit a manifest-style module that imports the zip via Bun's
// `with { type: "file" }` syntax. In dev that resolves to a disk path; inside
// `bun build --compile` binaries it resolves to a virtual `/$bunfs/...` path.
// Either way `Bun.file(zipRef)` returns a streamable BunFile (Blob subclass).
//
// Why this shape (vs. base64 string slab):
//   - Base64 materialised an ~86KB JS string literal PLUS a decoded Buffer
//     cache on first access. With Bun.file the zip is file-mapped — the only
//     bytes resident are whatever the consumer streams.
//   - Byte-reproducible: no timestamp, no UUID. Identical inputs ⇒ identical
//     output module ⇒ identical compiled binary (SLSA / attestation / cache).
const tsContent = `// AUTO-GENERATED by scripts/zip-extension.ts -- DO NOT EDIT
// Size: ${size} bytes

import zipRef from "../../dist/browser-extension.zip" with { type: "file" };

/**
 * Get the browser extension zip as a Blob (file-mapped — streamable directly
 * via \`new Response(blob)\` with no heap materialisation).
 */
export function getExtensionZip(): Blob {
  return Bun.file(zipRef);
}

export const extensionZipSize = ${size};
`;

writeFileSync(TS_OUTPUT, tsContent);
console.log(`[zip-extension] Generated ${TS_OUTPUT} (${(Buffer.byteLength(tsContent) / 1024).toFixed(1)}KB)`);
console.log("[zip-extension] Done!");
