#!/usr/bin/env bun
/**
 * zip-extension.ts - Zip the browser extension and embed as TS module
 *
 * 1. Creates dist/browser-extension.zip from packages/browser-extension/
 * 2. Generates src/embedded-extension.ts with the zip as base64
 *
 * Usage: bun run scripts/zip-extension.ts
 */

import { mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { $ } from "bun";

const EXT_DIR = join(import.meta.dir, "..", "packages", "browser-extension");
const ZIP_OUTPUT = join(import.meta.dir, "..", "dist", "browser-extension.zip");
const TS_OUTPUT = join(import.meta.dir, "..", "src", "embedded-extension.ts");

mkdirSync(join(import.meta.dir, "..", "dist"), { recursive: true });

// Create zip using system zip command
await $`cd ${EXT_DIR} && zip -r ${ZIP_OUTPUT} . -x "README.md" -x ".git/*" -x "node_modules/*" -x ".DS_Store"`.quiet();

const zipBuffer = readFileSync(ZIP_OUTPUT);
const base64 = zipBuffer.toString("base64");
const size = zipBuffer.length;

console.log(`[zip-extension] Created ${ZIP_OUTPUT} (${(size / 1024).toFixed(1)}KB)`);

// Generate embedded TS module
const tsContent = `// AUTO-GENERATED by scripts/zip-extension.ts -- DO NOT EDIT
// Generated at: ${new Date().toISOString()}
// Size: ${size} bytes

const EXTENSION_ZIP_BASE64 = "${base64}";

let _buffer: Buffer | null = null;

/** Get the browser extension zip as a Buffer (decoded lazily and cached). */
export function getExtensionZip(): Buffer {
  if (!_buffer) {
    _buffer = Buffer.from(EXTENSION_ZIP_BASE64, "base64");
  }
  return _buffer;
}

export const extensionZipSize = ${size};
`;

writeFileSync(TS_OUTPUT, tsContent);
console.log(`[zip-extension] Generated ${TS_OUTPUT} (${(Buffer.byteLength(tsContent) / 1024).toFixed(1)}KB)`);
console.log("[zip-extension] Done!");
